# docker-compose.yml (development)
version: '3.8'
services:
  frontend:
    build: 
      context: ./ReactTool/frontend
      args:
        - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./ReactTool/frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./ReactTool/backend
    ports:
      - "8000:5000"
    volumes:
      - ./ReactTool/backend:/app
      - ./data/db:/app/data
    environment:
      - FLASK_ENV=development
